version: '3'
services:
  memcached:
    image: memcached
  db:
    image: postgres:14
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=urmom
      - POSTGRES_USER=urmom
      - POSTGRES_PASSWORD=urmom
  php:
    build: web
    volumes:
      - ./web/html:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=urmom
      - DB_USER=urmom
      - DB_PASS=urmom
      - MEMCACHED_HOST=memcached
    ports:
      - 8080:80
    depends_on:
     - db
